#!/usr/bin/env bash
#Display process and PID file

file="/var/run/myscript.pid"
echo $$ > "$file"

#handles signals
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"; exit' SIGINT

while :; do
	echo "To infinity and beyond"
	sleep 2
done
