#!/usr/bin/env bash
#Displays "To infinity and beyond" indefinetly with a sleep 2 between each iteration
#displays "I am invicible! ! !" when receiving SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
